name: Bump version and tag

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install bump2version
      run: pip install bump2version

    - name: Configure Git
      run: |
        git config --global user.name "heysus-me"
        git config --global user.email "vksjesus@gmail.com"

    - name: Bump version and create tag
      run: |
        bump2version patch --allow-dirty
        git push --follow-tags
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}